### ISSUE TITLE
fix Utility.getSoundFileTitleFromUri Runtime Exception

### ISSUE THREAD

**Issue by martinposchmann** [firebirdberlin/nightdream#145]
Choosing a malicous file as custom ring tone caused RuntimeExceptions in MediaMetadataRetriever on my htc one m7. Once such a file is choosen, the app crashes everytime the list of ring tone is displayed.

**Comment by firebirdberlin** [comment]
The exception won't be raised any more. I didn't try what happens when a malicous file is used as alarm sound. It would be severe if no alarm sound is played. I hope the AlarmService is prepared for this case.
