### ISSUE TITLE
Crash on Android 8.0 Tablet

### ISSUE THREAD

**Issue by RubenKelevra** [firebirdberlin/nightdream#153]
My Lenovo cannot run this app. The app just crash on preview of Daydream and also when it should be enabled by Android as Daydream.

The autostart function does not work either.

Clicking on the app icon do work fine.

**Comment by firebirdberlin** [comment]
Can you figure out more details ? Which settings are active ? Do you use web radio or weather ?

**Comment by RubenKelevra** [comment]
I tried a bit around and it seems to be stable after wiping the data and re-set every configuration. But it looks like neither daydreams-mode nor the "while in standby" setting is working on this device - which is somewhat a bummer... 

But this is fairly low priority I guess.

**Comment by firebirdberlin** [comment]
Which version of the app is currently running on your device ? I'm just fixing some issues which I observe. Currently the autostart has some problems on Oreo devices. With the latest master it should work. I'm going to prepare a play store version this evening.

**Comment by RubenKelevra** [comment]
Well, the store version. :)

So, it's just a matter of time, great! I currently have it set to just turn on when I plug in, which is okay by now. It looks now stable, I have no idea why it was crashing before.

**Comment by firebirdberlin** [comment]
Are there still open issues ? I'd like to close this ticket.
