### ISSUE TITLE
Samsung Note 9 constantly asking for password doesn't use biometric 

### ISSUE THREAD

**Issue by sherpadude** [firebirdberlin/nightdream#157]
I've noticed an issue in which when I put my phone on docking charging station which automatically initiates clock I have two more often than not use a password not Biometrics to unlock my phone do you know the cause for this

**Comment by firebirdberlin** [comment]
If you activate the feature 'lock screen' then you have to give device administrator permissions to my app. If a device admin lock the device, the fingerprint sensor is being blocked for the next unlock. I don't think there's a way around. Many other apps have that problem, too. 
https://stackoverflow.com/questions/42886334/lock-screen-without-disabling-fingerprint
