### ISSUE TITLE
Bright, Flashing Screen

### ISSUE THREAD

**Issue by Trajadoja** [firebirdberlin/nightdream#165]
On random occasions something in the app triggers my Android (Pixel - Original) screen to go bright white and start flashing. This is obviously bad behavior for a NIGHT CLOCK. This occurred twice in the last three nights, so I have now disabled the app completely for the time being.

**Comment by firebirdberlin** [comment]
Do you have further information which setting could be the reason for this behaviour ? Which brightness mode do you use ? Do you use automatic night mode ?

**Comment by Trajadoja** [comment]
Hi! I don't have much additional information due to the nature of this
issue. As it happens in the middle of the night and wakes me, you can
understand why it could be hard to gather details. I've disabled the app
for now as I can't continue to risk losing sleep over this (literally).
Here's what else I can tell you:

   - It SEEMS to be this app as the app is running and the (dim) clock is
   still on the screen as the flashing occurs.
   - I was using automatic start mode so I could put the phone on my
   charger dock at night and let it start automatically (assuming it was in
   the time range)
   - I had the brightness set VERY low as I did want to know I could see
   the time, but the main purpose was the alarm.
   - At home now your app isn't as relevant as I have a new Google
   Assistant based alarm clock and an Eight Sleep tracker for sleep-cycle
   slarms
   - However, I'd like to now use it manually when travelling. The flashing
   issue, so far, has only occurred on my home charging dock, so that's good
   news.

I hope this helps.

**Comment by firebirdberlin** [comment]
Is this issue connected to automatically turning off the screen during night mode ?
