### ISSUE TITLE
Snooze does not work with radio station as alarm sound

### ISSUE THREAD

**Issue by biggybean** [firebirdberlin/nightdream#166]
Activating Snooze by just tapping anywhere on the screen does not work when the alarm sound is a radio station. Instead, the whole screen seems to have the "stop alarm" action implemented, not even displaying the left-hand bottom symbol any more. This is somehow related with how the radio feature runs - in one case, the radio feature crashed for me and was unmutable until I killed the app. However, when I restarted it, the next alarm worked fully as intended - including Snooze.

**Comment by firebirdberlin** [comment]
Lately I was already working on this issue. I could resolve it for my testing device. Please wait for the next update and give feedback. Please register for the beta channel. 
Thanks,
Stefan

**Comment by biggybean** [comment]
Thanks! I'm already on beta, I'll wait for the next version.
