### ISSUE TITLE
Add option to keep alarm time on the screen

### ISSUE THREAD

**Issue by llowrey** [firebirdberlin/nightdream#171]
After a short time, the display goes into a minimal mode. In that mode the alarm time is no longer shown. I would like to have the option of keeping the alarm time on the screen.

There is another ticket requesting the remaining duration of the alarm. That would be good in addition to the actual alarm time. I would like to be able to look at the display, half asleep, and know that the alarm is on, what time it is set for, and how much longer I can sleep without taping the display to bring up the additional info.

**Comment by firebirdberlin** [comment]
I started to work on making the next alarm time persistent. For this feature I am disabling the 'external' alarm sources. I had bugs and is hard to maintain. My own alarms are grown up and are able to replace other alarms clocks. I am relying on my alarm clock for a few years now. 

With the next beta version the new feature can be tested publicly.
