### ISSUE TITLE
Add in-app payment info to the Wiki FAQ

### ISSUE THREAD

**Issue by llowrey** [firebirdberlin/nightdream#172]
I would like to see descriptions in the Wiki FAQ for the various payment options, currently listed as:

- Full version
- Weather and design package
- Web radio package
- Always On package
- Donation

It is not clear if 'Full version' gives all three packages. I assume so but I think it should be stated explicitly.

It's also not clear if 'Donation' also provides all packages or if it is a payment in addition to 'Full version' or any of the packages.

**Comment by firebirdberlin** [comment]
You're right. Additional information would be great. Probably the FAQ is a good start, but I don't think that many people read it. A complete redesign of the in-app payment dialog would be better but more expensive as well.

**Comment by firebirdberlin** [comment]
https://github.com/firebirdberlin/nightdream/wiki#in-app-payments

**Comment by firebirdberlin** [comment]
Added a German translation for the info as well.
