### ISSUE TITLE
Autostart blocked in Android Q

### ISSUE THREAD

**Issue by llowrey** [firebirdberlin/nightdream#175]
Autostart doesn't work in Android Q due to new restrictions for background activity starts.

[https://developer.android.com/preview/privacy/background-activity-starts](https://developer.android.com/preview/privacy/background-activity-starts)

When I plug my phone in I get a warning toast instead of the app launching.

**Comment by firebirdberlin** [comment]
Thanks for the report. As far as I can see I can request for the permission
android.settings.action.MANAGE_OVERLAY_PERMISSION
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    if (! android.provider.Settings.canDrawOverlays(mContext)) {
        startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION));
    }
}
```

**Comment by llowrey** [comment]
Thanks! I'd be happy to test this for you when it comes time. It's not urgent since I can disable this new restriction via the developer options menu. That should work for a couple more months since I don't think they're remove that option until the final release of Q.
