### ISSUE TITLE
A mute radio audio feature request

### ISSUE THREAD

**Issue by spinico** [firebirdberlin/nightdream#183]
Really like the app, I've set up a few radio stations that I like to listen during the day, and when I temporarily turn off audio (slinding my volume to 0), I noticed that a button appears on the radio list that allow to "unmute" audio. It would be nice to also be able to quickly "mute" the audio in a similar way (unless there is a similar option that I am not aware off).

**Comment by firebirdberlin** [comment]
Great idea. This feature should be simple to resolve. The button is already there and can be used for muting the stream.
