### ISSUE TITLE
Cannot setup auto start time range 

### ISSUE THREAD

**Issue by spachner** [firebirdberlin/nightdream#19]
End time hour does not show up, just the seconds
V2.2.3
regards
spachner

**Comment by firebirdberlin** [comment]
Could you please submit a screenshot and your android version.  Thx,
Stefan

Am 28.08.2016 13:26 schrieb "spachner" <notifications@github.com>:

**Comment by spachner** [comment]
Hi,  ich habe dir nach jedem Touch einen Screenshot gemacht, es fehlt bei 
der Endzeit die Minuten Eingabe. Nach den Sekunden Startzeit kommt gleich 
die Eingabe Sekunden Endzeit. Im Kalender und so habe diese Probleme nicht.

Ich verwende Android 6.0.1 (cyanogenmod 13. 0).

Gruß

spachner


Am 30. August 2016 01:41:06 schrieb Stefan Fruhner <notifications@github.com>:

**Comment by firebirdberlin** [comment]
I didnt receive your screenshots. But anyway, I have an idea and started working on that issue, Hold on :)

**Comment by firebirdberlin** [comment]
I've uploaded a new BETA version 2.2.4. Is this issue fixed ?

**Comment by spachner** [comment]
Thanks, how can I test the beta?

spachner

**Comment by firebirdberlin** [comment]
To become a beta tester you can follow this url:
https://play.google.com/apps/testing/com.firebirdberlin.nightdream

Am 20.09.2016 4:28 nachm. schrieb "spachner" <notifications@github.com>:

**Comment by spachner** [comment]
Great, problem has been solved in beta ("Über" menu shows v2.2.5)
