### ISSUE TITLE
phone goes to standby when not being charged and nightdream is active

### ISSUE THREAD

**Issue by Fischreiher** [firebirdberlin/nightdream#235]
Hi, I'm using my second phone as a night clock. I'm keeping it on a wireless charger, and I would like the clock to be permanently on.
In this use case, I have seen tthe following minor issue:

My phone goes to standby when not being charged and nightdream is active.

In case of a power outage, I would like my phone to remain permanently on (as long as the battery permits).
However I have noticed that it goes to standby after 5 minutes (in case of my Galaxy S5) or after ~15 minutes (Galaxy S8).
I wonder whether this is a feature of the app, or a feature of the phone which the app is (so far) not preventing.
When charging resumes, the clock is shown again immediately which is good.
I'm just wondering about the different timeouts, and whether these could be increased to 'infinite'.
As I'm sometimes using my second phone otherwise, "standby mode while discharging" is not a good option for me.
Maybe there could be a new option, a variation of the "standby mode while discharging", like "keep phone on while discharging"?

Thanks a lot! Great App!

**Comment by firebirdberlin** [comment]
solved
