### ISSUE TITLE
Notifications no longer show outside of status bar mode

### ISSUE THREAD

**Issue by PikeUK** [firebirdberlin/nightdream#243]
NightDream v2.10.4 (running as a screensaver)
Android 10 on OnePlus 6T

As of the most recent update, notifications only work correctly if the "Status bar" mode is enabled in the Notifications options. If that option is not enabled then no notifications are displayed. This problem only started after the recent update. I've checked the "Notification access" permissions and it's still enabled.

Thanks.

**Comment by mastermichi** [comment]
Thanks for your feedback.
We will try to confirm the bug as soon as possible.
Can you post a screenshot from your layout to help us?

**Comment by PikeUK** [comment]
You can see that there is a Discord notification in the status bar but it doesn't appear below the weather as it used to. The strange thing is, the notifications temporarily appeared when I took the screenshot then disappeared again.
![Screenshot_20201215-175339](https://user-images.githubusercontent.com/15807255/102253006-b7ba7e80-3efe-11eb-9ad8-b70c49f8e087.jpg)

**Comment by mastermichi** [comment]
Is there any change if you disable weather and date ?

**Comment by PikeUK** [comment]
I tried all Layouts available in the Appearance tab. The problem only occurs with the "digital clock" layout, the other layouts (including "digital clock with ...") do NOT have the problem. Turning off "Show date" has no effect either way. Landscape or portrait has no effect either way. I couldn't find how to disable weather.

**Comment by mastermichi** [comment]
We can confim the bug. 
It will be fixed as soon as possible.

Weather can be disabled in the weather options:

![weather_settings_300](https://user-images.githubusercontent.com/68911754/102321062-71583480-3f7d-11eb-92f6-623dee11d230.png)

**Comment by mastermichi** [comment]
issue should be fixed in next version

**Comment by firebirdberlin** [comment]
should be fixed

**Comment by PikeUK** [comment]
Can confirm it's fixed now, thanks.
