### ISSUE TITLE
Notifications Error Android 11

### ISSUE THREAD

**Issue by mastermichi** [firebirdberlin/nightdream#297]
"Notifications in Night Clock don't display the correct icon, instead of showing whatever icon appears in the actual notification it just shows an i in a circle icon. In the attached screenshot the notification was for Gmail which has an envelope icon."

![Screenshot_20211012-174700](https://user-images.githubusercontent.com/68911754/139655390-d9ba2d0d-fce1-4378-b27e-4d653192b7ea.jpg)

Seems to be a problem with "Alerting notifications" (German: "Erinnerungsbenachrichtigung") 
-> No Problem with Android 9

**Comment by firebirdberlin** [comment]
Probably we have to switch to another method to retrieve the drawables. The current code is quite old. We could use api level M yet. Nowadays almost everybody has at least M.  
 
```
@RequiresApi(api = Build.VERSION_CODES.M)
private Drawable getSmallIcon(Context context, StatusBarNotification sbn) {
    Notification notification = sbn.getNotification();
    Icon icon = notification.getSmallIcon();
    return icon.loadDrawable(context);
}
```

**Comment by mastermichi** [comment]
Error: android.content.pm.PackageManager$NameNotFoundException
More informations:  https://stackoverflow.com/questions/62345805/namenotfoundexception-when-calling-getpackageinfo-on-android-11
Permission "QUERY_ALL_PACKAGES" needed: https://support.google.com/googleplay/android-developer/answer/10158779?hl=de

We also have to find a solution for "BrowseNotificationApps":
try {
    ai = pm.getApplicationInfo(app.getPackageName(), 0);
    if (ai != null) {
        holder.appicon.setImageDrawable(pm.getApplicationIcon(ai));
    }
} catch (PackageManager.NameNotFoundException ex) {
    Log.e(TAG, "Appicon not found. ", ex);
    holder.appicon.setImageResource(R.mipmap.ic_launcher);
}
