### ISSUE TITLE
Implement the post request for searching web radio streams

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#35]
The post request enables us to filter for countries and categories.

**Comment by m1ndlab** [comment]
I see what I can do...

**Comment by firebirdberlin** [comment]
It should be fairly simple if the country and the category parameters are omitted in the first step.

**Comment by firebirdberlin** [comment]
dirble.com/api-doc#search

**Comment by m1ndlab** [comment]
ok, so only replacing get with post, sounds easy. just got an own api key so for testing.

**Comment by firebirdberlin** [comment]
In next step I would add the requests for the full list of categories and countries. These need to be cached in order to avoid too many requests.

**Comment by firebirdberlin** [comment]
#47 merged.
