### ISSUE TITLE
Add a battery symbol to support the percentage value.

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#41]

**Comment by martinposchmann** [comment]
TODO: 
* fade-out
* show power symbol if loading
* tweak size and alignment (should be vertically centered in relation to the battery text?)

**Comment by firebirdberlin** [comment]
It already fades out. 

More todos:
  - Show the percentage and the estimation within the BatteryIconView

**Comment by firebirdberlin** [comment]
The latest commit contains an old version of the AndroidManifest. 
The layout-v9 still contains the old BatteryView. 

We should also think about if it's a good idea of coloring the icon red for a low battery value. If the user has chosen red as default color it will not be visible.
