### ISSUE TITLE
Allow to search for web radio streams without any country

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#49]
Currently always a country has to be selected.

**Comment by martinposchmann** [comment]
Maybe the dropdown should containt an entry "any country".

**Comment by firebirdberlin** [comment]
What about this:
The first line is simply empty instead of the string"any". The second line shows the user's country (preselected). Below follows an alphabetically sorted list of all other countries.

**Comment by firebirdberlin** [comment]
Resolved.
