### ISSUE TITLE
Manual brightness mode: Store the brightness level for day and night mode seperately

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#75]
If the brightness is set manually we may save the current brightness level for day and night mode separately and restore this settings accordingly.

**Comment by alx2000** [comment]
Automatic brightness is better to see with any ambient light, but at night in the dark room is preferred a manual brightness below the automatic brightness that ends up not being visible during the day's light. So a separate brightness in night mode would be great.

**Comment by firebirdberlin** [comment]
@alx2000 Today I uploaded a new beta for this issue.
