### ISSUE TITLE
Beaufort scale for wind speed

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/nightdream#83]
The Beaufort scale is still missing. It is widely used.

**Comment by martinposchmann** [comment]
The Beaufort value is now displayed in the WeatherForecastLayout in parentheses. 
Maybe there should be a switch in the preferences? 
However in wouldn't fit into WeatherLayout below the clock time. 
Possible options would be:
* reduce the font size of wind speed and display m/s and bft. with two rows
* display bft. only in landscape format, where the row can be longer
* replace m/s with bft. optionally, add preference option

**Comment by firebirdberlin** [comment]
I prefer the third point. I added an option for the beaufort scale and show it exclusivly. The commit is already merged.

**Comment by martinposchmann** [comment]
Great, Thanks!
