### ISSUE TITLE
No brightness regulation (Android 5.1, no light sensor)

### ISSUE THREAD

**Issue by Moarc** [firebirdberlin/nightdream#87]
Since the May 10 (Play Store) version I've been unable to set the brightness in day mode. The brightness section under Settings -> Appearance is empty too. My device does not include a light sensor, but everything worked (mostly) OK before this update.
![screenshot_2017-05-18-17-51-52-small](https://cloud.githubusercontent.com/assets/6317451/26211749/94820904-3bf3-11e7-92a4-b2561f301642.png)

**Comment by Moarc** [comment]
The issue went away after I reinstalled the app; there's still no brightness settings though.

**Comment by firebirdberlin** [comment]
These controls do not apply to devices without light sensor at all. The category brightness should be hidden completely.

**Comment by firebirdberlin** [comment]
I added a new issue #88

**Comment by Moarc** [comment]
I just realized that the brightness regulation works as it should when I run Night Clock from the app drawer, but when actually ran as a daydream, it's stuck at 100% brightness, and nothing happens when I slide the top of the screen.

**Comment by firebirdberlin** [comment]
I also observed that the daydream part of the app is less responsive. To be honest I'd like to abandon the daydream feature completely. Nowadays the activity provides all features which are provided by daydreams too. Daydream has a few bugs which I cannot resolve, e.g. the screen orientation is sometimes forced to be portrait.

**Comment by Moarc** [comment]
Thanks for this explanation - I started using the autostart functionality and now everything works as it should.
